config/routes.rb
Laitevuokraus::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :reservations

  resources :items
  
  root :to => "reservations#index"

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  
  has_event_calendar
  
  belongs_to :user
  has_and_belongs_to_many :items
  
  before_save :calculate_fee
  before_validation :generate_name
  validates_presence_of :name
  validate :must_have_one_item
  validate :date_at_least_today
  validate :ensure_duration_positive
  validate :fee_must_be_at_least_1_time
  before_create :no_overlap_for_items
  validates_presence_of :start_at, :end_at; :fee
  
  
  #boring validations
  validates_presence_of :firstname 
  validates_presence_of :lastname, :address, :phone, :email 
  validates_length_of :phone, :minimum => 6
  
  protected
  
    def duration
      return (self.end_at-self.start_at)/60/60/24.ceil.to_i
    end
    
    def generate_name
      
      self.name = ""
      
      for item in self.items
        self.name = self.name+item.title+" "
      end
      
      self.name = self.name+" are being rented"
      
    end
    
    def date_at_least_today
      errors.add(:start_at, "must be at least present moment") if
        self.start_at < Time.now
    end
    
    def must_have_one_item
      errors.add(:items, "must be selected") if 
        self.items.length < 1
    end 
  
  
    def ensure_duration_positive
      errors.add(:end_at, "must be after start") if
        duration <= 0
    end
    
    def fee_must_be_at_least_1_time

    end
    
  
    def calculate_fee
      fee = 0.to_f
      for item in self.items 
        fee = fee+item.price*duration.to_f
      end
    
      #round fee to closest integer, typecast back to float
      fee = fee.ceil.to_f
    
      self.fee = fee
    
    end
    
    def no_overlap_for_items
      overlap = false
      reservations = Reservation.all
      
      for reservation in reservations
        
        #does the reservation being compared have the same item?
        for item in reservation.items
          if self.items.include?(item)
              
              #is the included item also in use in the same time?
              if ((reservation.start_at - self.end_at) * (self.start_at - reservation.end_at) >= 0)
                overlap = true
              end
                
          end
        end
      end
      
      errors.add(:start_at, "There is a prior reservation for this equipment during this time") if
        overlap == true
        
    end
    
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.xml
  def index
    
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Reservation.event_strips_for_month(@shown_month)
    
    
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.xml
  def show
    @reservation = Reservation.find(params[:id])
    @items = @reservation.items

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.xml
  def new
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Reservation.event_strips_for_month(@shown_month)
    
    
    @items = Item.all
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Reservation.event_strips_for_month(@shown_month)
    
    @reservation = Reservation.find(params[:id])
    @items = Item.all
  end

  # POST /reservations
  # POST /reservations.xml
  def create
    
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Reservation.event_strips_for_month(@shown_month)
    
    @reservation = Reservation.new(params[:reservation])



    respond_to do |format|
      if @reservation.save
        format.html { redirect_to(@reservation, :notice => 'Reservation was successfully created.') }
        format.xml  { render :xml => @reservation, :status => :created, :location => @reservation }
      else
        @items = Item.all
        format.html { render :action => "new" }
        format.xml  { render :xml => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.xml
  def update
    
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Reservation.event_strips_for_month(@shown_month)
    
    @reservation = Reservation.find(params[:id])
    @items = @reservation.items
    

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to(@reservation, :notice => 'Reservation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.xml
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to(reservations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<%= raw(event_calendar) %>

<h2>Times for reservation start (gear pickup) and end (gear return)</h2>

  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at, :default => 1.day.from_now  %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at, :default => 2.day.from_now %>
  </div>

<h2>Gear to be rented</h2>

<% for item in @items %>
<div>
  <%= check_box_tag "reservation[item_ids][]", item.id, @reservation.items.include?(item) %>
  <%= item.title %>, <%= item.price %> &euro;/vrk
</div>
<% end %>


<h2>Personal details</h2>

<div class="field">
  <%= f.label :firstname %><br />
  <%= f.text_field :firstname %>
</div>
<div class="field">
  <%= f.label :lastname %><br />
  <%= f.text_field :lastname %>
</div>
<div class="field">
  <%= f.label :address %><br />
  <%= f.text_field :address %>
</div>
<div class="field">
  <%= f.label :phone %><br />
  <%= f.text_field :phone %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>

  <div class="actions">
    <%= submit_tag "Submit!", :confirm => "The reservation is binding – Are you sure you want to submit the reservation?" %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<%= stylesheet_link_tag "event_calendar" %>

<h1>Reservations</h1>

<%= link_to 'New Reservation', new_reservation_path %>

<%= raw(event_calendar) %>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @reservation.firstname %>
</p>
<p>
  <b>Last name:</b>
  <%= @reservation.lastname %>
</p>
  <b>Address:</b>
  <%= @reservation.address %>
</p>
  <b>Phone:</b>
  <%= @reservation.phone %>
</p>
  <b>Email:</b>
  <%= @reservation.email %>
</p>


<p>
  <b>Start:</b>
  <%= @reservation.start_at %>
</p>

<p>
  <b>End:</b>
  <%= @reservation.end_at %>
</p>

<p>
  <b>Items:</b>
  <% for item in @items %>
<div>
  <%= item.title %>
</div>
<% end %>
</p>

<p>
  <b>Fee:</b>
  <%= @reservation.fee %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %> |
<%= link_to 'Destroy', @reservation, :confirm => "Are you sure?", :method => :delete %>